import pygame





# game grid - MAIN
GRID_ROW = 25
GRID_COL = 50
BOARD_WIDTH=1250
BOARD_LENGTH=800
GRID_COLOR =(138,201,38)
GRASS_PIC ="grass.png"
FPS=60
main_screen=pygame.display.set_mode((BOARD_WIDTH,BOARD_LENGTH))
SOLDIER_WIDTH=80
SOLDIER_HEIGHT=100
X_MOVEMENT=10
Y_MOVEMENT=10


#game grid - mines
MINES_GRID_ROW = 25
MINES_GRID_COL = 50
MINES_GRID_COLOR =(0,0,0)
MINES_GRID_LINES_COLOR = "dark green"
MINES_HEIGHT = 1
MINES_LENGTH = 3